services:
    api:
        build:
            context: .
            dockerfile: ./apps/vanguard-api/Dockerfile
        ports:
            - "3001:3001"

    bot:
        build:
            context: .
            dockerfile: ./apps/vanguard-bot/Dockerfile
