services:
    api:
        build:
            context: .
            dockerfile: ./apps/vanguard-api/Dockerfile
        env_file:
            - ./apps/vanguard-api/.env
        ports:
            - "3001:3001"

    bot:
        build:
            context: .
            dockerfile: ./apps/vanguard-bot/Dockerfile
        env_file:
            - ./apps/vanguard-bot/.env

    dashboard:
        build:
            context: .
            dockerfile: ./apps/vanguard-dashboard/Dockerfile
        env_file:
            - ./apps/vanguard-dashboard/.env
        ports:
            - "3101:3101"
